### ISSUE TITLE
...?

### ISSUE THREAD

**Issue by Juha3141** [DevSDK/0SOS#1]
mint64os느낌이 나는거는 기분 탓일거라 믿습니다
아니 잠깐 이건 그냥 배낀거잖아

저기요?? 운영체제는 누군가의 코드를 배끼는게 아닙니다, 적어도 출처는 써놔야죠!

**Comment by DevSDK** [comment]
꽤 오래전에 작성한 코드인데 관심 가져주셔서 감사합니다. 

이 프로젝트는 "64비트 멀티코어 OS 원리와 구조" 서적을 보면서 개발하는 프로젝트였습니다.
mint64os는 그 책에 나오는 OS입니다.

따라서 mint64os와 0SOS와 유사하거나 동일한 구조가 많습니다.

저는 책 내용을 구현한 것이고,
책 저자 분하고 이야기 하면서 개발한것이라 별도로 표기하지는 않았습니다.
감사합니다.

**Comment by Juha3141** [comment]
:\

**Comment by 614project** [comment]
그냥 출처 남기시지...

**Comment by DevSDK** [comment]
서적 출처 반영했습니다.

**Comment by DevSDK** [comment]
![image](https://user-images.githubusercontent.com/18409763/109748097-9cb4fc00-7c1b-11eb-9fe4-fae6cd09f749.png)
원 저자분과 다시한번 이야기 되었습니다.
감사합니다.
